#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
- name: dtarasov
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFVHTsCNTaI9oVuNKDDtdSVSTN8Csu337MYObrS+7v8w mrsndmn46@gmail.com