---
- name: Add github-runner user
  hosts: [ 'github_runners', 'github_runners_gpu', 'github_runners_gpu_agent' ]
  tags: [ 'github-runner', 'github-runner-gpu', 'github-runner-gpu-agent' ]
  become: yes
  tasks:
    - name: create github runner user
      user:
        name: github-runner

- name: Make data path
  hosts: [ 'github_runners', 'github_runners_gpu', 'github_runners_gpu_agent' ]
  tags: [ 'github-runner', 'github-runner-gpu', 'github-runner-gpu-agent' ]
  become: yes
  tasks:
    - name: mkdir data
      ansible.builtin.file:
        path: /data
        state: directory
        owner: root
        group: root
    - name: mkdir data/var
      ansible.builtin.file:
        path: /data/var
        state: directory
        owner: root
        group: root


- name: Install packages
  hosts: [ 'github_runners', 'github_runners_gpu', 'github_runners_gpu_agent' ]
  become: yes
  tags: [ 'github-runner', 'github-runner-gpu', 'github-runner-gpu-agent', 'apt' ]
  tasks:
    - name: install conda dependencies
      apt:
        name: libgl1
        state: present
        update_cache: true
    - name: install conda dependencies
      apt:
        name: libglx-mesa0
        state: present
        update_cache: true
    - name: install unzip
      apt:
        name: unzip
        state: present
        update_cache: true
    - name: install tmux
      apt:
        name: tmux
        state: present

- name: Install GitHub Actions Runner
  hosts: github_runners
  tags: [ 'github-runner' ]
  become: yes
  vars:
    runner_user: "github-runner"
    runner_dir: /data/var/actions-runner
    runner_pkg_tempdir: /tmp/gh_actions_runner
    runner_version: "latest"
    runner_state: "started"
    reinstall_runner: yes
    hide_sensitive_logs: no
    github_url: "https://github.com"
    github_api_url: "https://api.github.com"
    runner_org: yes
    runner_labels: [ 'self-hosted-cpu', 'self-hosted' ]
    runner_download_repository: "actions/runner"
    runner_extra_config_args: ""
    runner_name: "ansible-runner {{inventory_hostname}}"
    runner_on_ghes: no
    github_account: "fintech-dl-hse"
  roles:
    - role: ansible-github_actions_runner


- name: Install GitHub Actions Runner GPU
  hosts: [ 'github_runners_gpu' ]
  tags: [ 'github-runner-gpu' ]
  become: yes
  vars:
    runner_user: "github-runner"
    runner_dir: /data/var/actions-runner
    runner_pkg_tempdir: /tmp/gh_actions_runner
    runner_version: "latest"
    runner_state: "started"
    reinstall_runner: no
    hide_sensitive_logs: no
    github_url: "https://github.com"
    github_api_url: "https://api.github.com"
    runner_org: yes
    runner_labels: [ 'self-hosted-gpu' ]
    runner_download_repository: "actions/runner"
    runner_extra_config_args: ""
    runner_name: "ansible-runner {{inventory_hostname}}"
    runner_on_ghes: no
    github_account: "fintech-dl-hse"
  roles:
    - role: ansible-github_actions_runner


- name: Install GitHub Actions Runner GPU Agent
  hosts: [ 'github_runners_gpu_agent' ]
  tags: [ 'github-runner-gpu-agent' ]
  become: yes
  vars:
    runner_user: "github-runner"
    runner_dir: /data/var/actions-runner
    runner_pkg_tempdir: /tmp/gh_actions_runner
    runner_version: "latest"
    runner_state: "started"
    reinstall_runner: no
    hide_sensitive_logs: no
    github_url: "https://github.com"
    github_api_url: "https://api.github.com"
    runner_org: yes
    runner_labels: [ 'self-hosted-gpu-agent' ]
    runner_download_repository: "actions/runner"
    runner_extra_config_args: ""
    runner_name: "ansible-runner {{inventory_hostname}}"
    runner_on_ghes: no
    github_account: "fintech-dl-hse"
  roles:
    - role: ansible-github_actions_runner


# - name: Restart always for all runners units
#   hosts: [ 'github_runners', 'github_runners_gpu', 'github_runners_gpu_agent' ]
#   tags: [ 'github-runner-gpu-agent', 'github-runner-gpu', 'github-runner' ]
#   become: yes
#   tasks:
#     - name: Restart always for all runners units
#       block:
#         - name: Run the installer
#           shell: grep -q '^\[Service\]' /etc/systemd/system/your-service.service && !grep -q '^Restart=' /etc/systemd/system/your-service.service && sed -i '/^\[Service\]/a Restart=always' /etc/systemd/system/your-service.service
#         - name: Restart the service
#           shell: systemctl daemon-reload && systemctl restart your-service


- name: Install Miniconda and Dependencies CPU
  hosts: [ 'github_runners' ]
  tags: [ 'miniconda' ]
  become: yes
  tasks:
    - name: Install Conda
      block:
        - name: Download Miniconda
          get_url:
            url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            dest: /tmp/install-miniconda.sh
            mode: 0550
        - name: Create conda folder
          become: True
          file:
            path: /data/bin/miniconda3
            state: directory
            owner: github-runner
            mode: 755
            recurse: yes
        - name: Run the installer
          shell: /tmp/install-miniconda.sh -b -u -p /data/bin/miniconda3
        - name: Remove the installer
          file:
            state: absent
            path: /tmp/install-miniconda.sh
        - name: Add miniconda bin to path
          become: True
          shell: echo 'export PATH=/data/bin/miniconda3/bin:$PATH' >> /etc/profile
        - name: conda - read permission for all
          become: True
          file:
            path: /data/bin/miniconda3
            mode: +r
            recurse: yes
        - name: conda - create jupyter-actions env
          become: True
          shell: /data/bin/miniconda3/bin/conda create -p /data/bin/miniconda3/envs/jupyter-actions python=3.11
        - name: conda env jupyter-actions - install pytorch
          become: True
          shell: /data/bin/miniconda3/envs/jupyter-actions/bin/pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        - name: conda env jupyter-actions - install other dependencies
          become: True
          shell: /data/bin/miniconda3/envs/jupyter-actions/bin/pip3 install jupyter nbformat nbconvert numpy requests pytest scikit-learn pandas opencv-python tqdm tensorboard matplotlib scipy datasets pytorch-lightning transformers evaluate sacrebleu accelerate wandb
        - name: conda - execution permission for all
          become: True
          file:
            path: /data/bin/miniconda3
            mode: +x
            owner: github-runner
            group: github-runner
            recurse: yes
        - name: Install latest git version
          become: True
          shell: apt-add-repository ppa:git-core/ppa -y && apt-get update -y && apt-get install -y git


- name: Install Miniconda and Dependencies GPU
  hosts: [ 'github_runners_gpu', 'github_runners_gpu_agent' ]
  tags: [ 'miniconda' ]
  become: yes
  tasks:
    - name: Install Conda
      block:
        - name: Download Miniconda
          get_url:
            url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            dest: /tmp/install-miniconda.sh
            mode: 0550
        - name: Create conda folder
          become: True
          file:
            path: /data/bin/miniconda3
            state: directory
            owner: github-runner
            mode: 755
            recurse: yes
        - name: Run the installer
          shell: /tmp/install-miniconda.sh -b -u -p /data/bin/miniconda3
        - name: Remove the installer
          file:
            state: absent
            path: /tmp/install-miniconda.sh
        - name: Add miniconda bin to path
          become: True
          shell: echo 'export PATH=/data/bin/miniconda3/bin:$PATH' >> /etc/profile
        - name: conda - read permission for all
          become: True
          file:
            path: /data/bin/miniconda3
            mode: +r
            recurse: yes
        - name: conda - create jupyter-actions env
          become: True
          shell: /data/bin/miniconda3/bin/conda create -p /data/bin/miniconda3/envs/jupyter-actions python=3.11
        - name: conda env jupyter-actions - install pytorch
          become: True
          shell: /data/bin/miniconda3/envs/jupyter-actions/bin/pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu118
        - name: conda env jupyter-actions - install other dependencies
          become: True
          shell: /data/bin/miniconda3/envs/jupyter-actions/bin/pip3 install jupyter nbformat nbconvert numpy requests pytest scikit-learn pandas opencv-python tqdm tensorboard matplotlib scipy datasets pytorch-lightning transformers evaluate sacrebleu accelerate wandb
        - name: conda - execution permission for all
          become: True
          file:
            path: /data/bin/miniconda3
            mode: +x
            owner: github-runner
            group: github-runner
            recurse: yes
        - name: Install latest git version
          become: True
          shell: apt-add-repository ppa:git-core/ppa -y && apt-get update -y && apt-get install -y git
