name: Check hw rnn attention

on:
  workflow_call:

jobs:
  start-runner-internal:
    uses: fintech-dl-hse/checkhw/.github/workflows/start-runner.yaml@main

  run_autograding:
    needs: [ "start-runner-internal" ]
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    name: Autograding
    runs-on: self-hosted
    steps:
      - name: Checkout HW
        uses: fintech-dl-hse/action-checkout-hw@v1.3
        with:
          autograding-file: autograding-batchnorm-dropout.json

      - name: Extract dropout class
        run: /data/bin/miniconda3/envs/jupyter-actions/bin/python extract_class_from_notebook.py --notebook "hw_batchnorm_dropout.ipynb" --class_definition "class DropoutLayer(nn.Module):" --out_filename "dropout.py"

      - name: Extract batchnorm2d class
        run: /data/bin/miniconda3/envs/jupyter-actions/bin/python extract_class_from_notebook.py --notebook "hw_batchnorm_dropout.ipynb" --class_definition "class BatchNorm2dLayer(nn.Module):" --out_filename "batchnorm2d.py"

      - name: Autograding
        uses: education/autograding@v1

      - name: Save dropout.py
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: dropout.py
          path: dropout.py

      - name: Save batchnorm2d.py
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: batchnorm2d.py
          path: batchnorm2d.py
