name: Check hw rnn attention

on:
  workflow_call:

jobs:
  start-runner-internal:
    uses: fintech-dl-hse/checkhw/.github/workflows/start-runner.yaml@main

  run_autograding:
    needs: [ "start-runner-internal" ]
    name: Autograding
    runs-on: self-hosted
    steps:
      - name: Checkout HW
        uses: fintech-dl-hse/action-checkout-hw@v1.3
        with:
          autograding-file: autograding-weight-init.json

      - name: Autograding
        uses: education/autograding@v1
