name: Check hw rnn attention

on:
  workflow_call:

jobs:
  start-runner-internal:
    uses: fintech-dl-hse/checkhw/.github/workflows/start-runner.yaml@main

  run_autograding:
    needs: [ "start-runner-internal" ]
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    name: Autograding
    runs-on: self-hosted
    steps:
      - name: Checkout HW
        uses: fintech-dl-hse/action-checkout-hw@2e5bb868e35cb66e4289ab4a72c8bd6f558b283e
        with:
          autograding-file: autograding-activations.json

      - name: Autograding
        uses: education/autograding@v1
