name: Start GitHub Runners

on:
  workflow_call:
    inputs:
      autograding-file:
        description: 'File name of autograding for homework'
        required: true
        type: string

jobs:
  prepare-hw-repo:
    if: github.repository_owner  == 'fintech-dl-hse'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout classroom files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/classroom
          path: checkhw
          repository: fintech-dl-hse/checkhw

      - name: Mkdir .github/classroom
        run: mkdir -p .github/classroom || true

      - name: Restore autograding file
        run: cp checkhw/.github/classroom/{{ inputs.autograding-file }} .github/classroom/autograding.json
