name: Start GitHub GPU Agent Runner

on:
  workflow_call:
  workflow_dispatch:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    if: github.repository_owner  == 'fintech-dl-hse'
    steps:
      - name: Start Cloud GPU Agent Runners
        run: curl https://functions.yandexcloud.net/d4eoj3esc5rokpgn1qt8