name: Start GitHub Runners

on:
  workflow_call:
  workflow_dispatch:

jobs:
  debug-env:
    runs-on: ubuntu-latest
    steps:
      - name: dbg
        run: echo "ORGANIZATION_VAR = ${{ vars.ORGANIZATION_VAR }}"

  start-runner:
    runs-on: ubuntu-latest
    if: vars.ORGANIZATION_VAR  == 'fintech-dl-hse'
    steps:
      - name: Start Cloud Runners
        run: curl https://functions.yandexcloud.net/d4ekjk6fah67t6pdv3o1