name: Start GitHub Runners

on:
  workflow_call:
  workflow_dispatch:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    if: github.repository_owner  == 'fintech-dl-hse'
    steps:
      - name: Start Cloud Runners
        run: curl https://functions.yandexcloud.net/d4efmogpb68sf7ajt1um
