name: Stop GitHub Runners

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  stop-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Check any runner is busy
        run: |
          curl -L  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/fintech-dl-hse/actions/runners | jq '.runners | any(.status == "online" and .busy == false) '
      - name: Stop Cloud Runners
        run: curl https://functions.yandexcloud.net/d4e9t5qi6hnqvi3b1633