name: Stop GitHub Runners

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  start-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Cloud Runners
        run: curl https://functions.yandexcloud.net/d4e9t5qi6hnqvi3b1633