name: Stop GitHub Runners

on:
  schedule:
    - cron: "30 */4 * * *"
  workflow_dispatch:
  workflow_call:


jobs:
  stop-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Check any runner is busy
        continue-on-error: true
        run: |
          curl -L  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/fintech-dl-hse/actions/runners | jq '.runners | any(.status == "online" and .busy == false) ' -e
          if [ $? -eq 0 ]; then
              curl https://functions.yandexcloud.net/d4eiq39h16hj0tphf8js
          fi
          exit 0
