name: Apply terraform

on:
  push:
    branches:
      - main

jobs:

  apply-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Init terraform
        run: |
          cd terraform
          cp .terraformrc ~/
          terraform init -backend-config="access_key=$YC_SA_ACCESS_KEY" -backend-config="secret_key=$YC_SA_SECRET_KEY"

          make zip-functions
          terraform apply -auto-approve

